fix: EE.on/once inference with extended EventEmitter classes
ckohen/DefinitelyTyped pull request #1
Opened 2024-08-01 08:22 UTC by vladfrangu

2024-08-02 12:29 UTC, ckohen requested changes

2024-08-02 12:29 UTC, ckohen commented on types/node/events.d.ts
> +
This should not be between the comment and the module, it associates the comment with the symbol instead of the events module :(. (Which doesn't work for node:events anyways lol)

Also can we make it clear by the symbol name what is going on here? I.E. `internalTypeOnlyEventEmitterBrandSymbol` (maybe without EventEmitter cause that's long lol)

2024-08-02 12:29 UTC, ckohen commented on types/node/test/events_generic.ts
> +    class Extended extends events.EventEmitter<{ wow: [string, boolean] }> {}
Any specific reason not to reuse T? I don't mind it since I can barely remember what's in T by the time I've scrolled here...

I only ask because tests for instance methods on these extensions should probably exist too (don't care who does those, it's copy-paste, change variable name)

2024-08-02 12:40 UTC, vladfrangu commented on types/node/test/events_generic.ts
> +    class Extended extends events.EventEmitter<{ wow: [string, boolean] }> {}
No specific reason for not reusing T, will change

2024-08-02 12:40 UTC, vladfrangu commented on types/node/events.d.ts
> +
Will do, will move the symbol at the top of the file and give it a better name

2024-08-04 14:31 UTC, ckohen approved these changes

2024-08-04 14:32 UTC, merged